
# Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: canary
  annotations:
    # mark this ingress as the canary and assign ~20% traffic to it
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "20"
spec:
  ingressClassName: nginx
  rules:
  - host: nginx.local
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: canary-service
            port:
              number: 80
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stable
spec:
  ingressClassName: nginx
  rules:
  - host: nginx.local
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: stable-service
            port:
              number: 80

